-- The unguessable half of `/onboarding/payments/<token>` (ADR-011 amendment, E4).
--
-- That page mints a Stripe Account Link and 302s to it. An Account Link is a
-- BEARER capability: whoever opens it can submit this restaurant's KYC and set
-- the bank account its money is paid into. So the page must not be addressable
-- by slug — `/onboarding/payments?slug=rumi` would be an open door onto a real
-- restaurant's payout details, and the restaurant has no login here to put in
-- front of it (they log into their own tenant app, never into the control plane).
--
-- 32 random bytes, base64url, generated by lib/connect-account-store.ts at the
-- moment the account is minted. Long-lived on purpose, unlike the 300-second
-- link it produces (MEASURED: `expires_at - created = 300`, and two calls return
-- two different URLs), because it travels in the tenant's own env
-- (`Stripe__PaymentsLinkUrl`) and in a welcome mail, both of which outlive five
-- minutes. Its blast radius is one restaurant's onboarding, and it sits in a box
-- `.env` beside the platform Stripe key — strictly less powerful than its
-- neighbour.
--
-- ADDITIVE ONLY, and safe on a DB with live rows: one NULLABLE column and one
-- unique index on "StripeConnectAccount" (20260905190000). No column is retyped,
-- no constraint is dropped, no row changes meaning, and nothing is backfilled.
--
-- NULLABLE, deliberately, even though every row this app writes will carry a
-- token: the column arrived after the table, so a row written in between has
-- none, and NULL is the honest record of that. A unique index in Postgres allows
-- many NULLs, so this neither collides nor blocks. The read path
-- (`findConnectAccountByToken`) treats a NULL token as NO MATCH, so such a row is
-- unreachable by the page rather than reachable without a token — and the same
-- 404 answers "no such token" and "a row from before tokens", because a page that
-- told them apart would confirm to a stranger that a token is nearly right.

ALTER TABLE "StripeConnectAccount" ADD COLUMN "onboardingToken" TEXT;

CREATE UNIQUE INDEX "StripeConnectAccount_onboardingToken_key"
  ON "StripeConnectAccount"("onboardingToken");
